function calfun(obj) {
  var el1 = document.getElementById(obj);
  el1.style.display = "block";
  switch (obj) {
    case "fist":
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "ka":
      document.getElementById("fist").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "gna":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "cha":
      document.getElementById("fist").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "gya":
      document.getElementById("fist").style.display = "none";

      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "ta":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "naa":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "naa":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;

    case "tha":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "na1":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;

    case "pa":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "ma":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "ya":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "ra":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "la":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "va":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "zha":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "ila":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "ira":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "ina":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "jha":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "sha":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "sa":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("jha").style.display = "none";
      document.getElementById("ha").style.display = "none";
      break;
    case "ha":
      document.getElementById("fist").style.display = "none";
      document.getElementById("ka").style.display = "none";
      document.getElementById("gna").style.display = "none";
      document.getElementById("cha").style.display = "none";
      document.getElementById("gya").style.display = "none";
      document.getElementById("ta").style.display = "none";
      document.getElementById("naa").style.display = "none";
      document.getElementById("tha").style.display = "none";
      document.getElementById("na1").style.display = "none";
      document.getElementById("pa").style.display = "none";
      document.getElementById("ma").style.display = "none";
      document.getElementById("ya").style.display = "none";
      document.getElementById("ra").style.display = "none";
      document.getElementById("la").style.display = "none";
      document.getElementById("va").style.display = "none";
      document.getElementById("zha").style.display = "none";
      document.getElementById("ila").style.display = "none";
      document.getElementById("ira").style.display = "none";
      document.getElementById("ina").style.display = "none";
      document.getElementById("sha").style.display = "none";
      document.getElementById("sa").style.display = "none";
      document.getElementById("jha").style.display = "none";
      break;
  }
}
function calfunout(ele) {
  var el = document.getElementById(ele);
  el.style.display = "none";
}

function pass(strvalue) {
  var text = document.getElementById("myText").value;
  document.getElementById("myText").value = text + strvalue;
}
function myFunction() {
  return false;
}

function reset() {
  document.getElementById("myText").value = "";
}


function removeOne(){
   var text = document.getElementById("myText").value;
   var newStr = text.substring(0, text.length-1);
   document.getElementById("myText").value = newStr;
}